[Icon Theme]
Name=Papirus-Dark-Candy
Comment=Papirus Dark with Candy application icons
Inherits=Papirus-Dark,Papirus,breeze,gnome,hicolor
FollowsColorScheme=true

Example=folder

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64
DialogDefault=48
DialogSizes=16,22,24,32,48,64

Directories=apps/scalable,devices/scalable,status/scalable,Places/48,Places/16,mimetypes/scalable

[apps/scalable]
Context=Applications
Size=96
MinSize=8
MaxSize=512
Type=Scalable

[devices/scalable]
Size=96
Context=Applications
MinSize=8
MaxSize=512
Type=Scalable

[status/scalable]
Size=64
Context=Status
Type=Scalable
Type=Scalable
MinSize=16
MaxSize=128

[Places/48]
Size=48
Context=Places
MinSize=32
MaxSize=512
Type=Scalable

[Places/16]
Size=16
Context=Places
MinSize=8
MaxSize=32
Type=Scalable

[mimetypes/scalable]
Size=96
Context=MimeTypes
Type=Scalable
MinSize=8
MaxSize=256
